### ISSUE TITLE
Issues from 2021-10-07 dev call

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/mpl-brochure-site#5]
Web page:

- [x] no hover animation on news links
- [x] swap new <-> resources left / right
- [ ] #37

Content:

- [x] add link to blog
- [x] drop FAQ link
- [ ] add search box (maybe?  Do not think we want to move the js + data needed to do that to this site)
- [ ] switch link to point at https://github.com/matplotlib/matplotlib/pull/21313/files when merged.

**Comment by jklymak** [comment]
- [ ] shorten news to better balance resources...

**Comment by tacaswell** [comment]
> switch link to point at https://github.com/matplotlib/matplotlib/pull/21313/files when merged.

I no longer remember which link this was referring to

**Comment by jklymak** [comment]
See #38....  I'll mark that as closing this issue
