### ISSUE TITLE
Navigation doesn't work on mobile 

### ISSUE THREAD

**Issue by story645** [matplotlib/mpl-brochure-site#67]
When I click on either menu, my screen gets grayed out on chrome and Firefox. This only happens on the brochure site and not the docs

![Screenshot_20220928-113820.jpg](https://user-images.githubusercontent.com/1300499/192824015-f65f60c8-e585-4bc2-9f4d-c7b0b207d8c3.jpg)

**Comment by timhoffm** [comment]
Confirmed. Same on Safari.

**Comment by QuLogic** [comment]
The right button should be empty because we have no right sidebar. I think that showing it is maybe a bug in the theme.

**Comment by QuLogic** [comment]
The theme lag is definitely a pydata-sphinx-theme bug.
