### ISSUE TITLE
Search and light/dark buttons not working

### ISSUE THREAD

**Issue by rcomer** [matplotlib/mpl-brochure-site#73]
On https://matplotlib.org/ homepage, clicking either the search button or the light/dark mode button in the top bar doesn't do anything.  Both are fine once I've clicked through to the stable docs.  I see the same behaviour on Linux Firefox, Windows Chrome and IOS Safari.

**Comment by QuLogic** [comment]
I noticed this yesterday when uploading 3.6.3 docs; I'm sure it used to work, but I'm not sure when it broke.

**Comment by QuLogic** [comment]
The browser console shows an error about undefined `jQuery`; I'd guess one of our theme components dropped that and another was relying on it.

**Comment by rcomer** [comment]
It definitely used to work.  I noticed this last week and I use the search from there fairly often so I don’t think it’s been broken very long.

**Comment by QuLogic** [comment]
The last build was two weeks ago after a merge. Fetching those commits directly from GitHub and diffing them shows:
```
$ git diff --stat last-month..two-weeks-ago 
 .buildinfo                                      |     2 +-
 404.html                                        |     3 -
 _static/_sphinx_javascript_frameworks_compat.js |   134 ----
 _static/basic.css                               |     3 +
 _static/jquery-3.6.0.js                         | 10881 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 _static/jquery.js                               |     2 -
 _static/script.js                               |    11 +-
 _static/underscore-1.13.1.js                    |  2042 -------------------------------------------------
 _static/underscore.js                           |     6 -
 genindex.html                                   |     3 -
 index.html                                      |     3 -
 search.html                                     |     3 -
 12 files changed, 9 insertions(+), 13084 deletions(-)
```
So we definitely lost jquery from somewhere.

**Comment by QuLogic** [comment]
The last build caught Sphinx 6, which [dropped jQuery and underscore.js](https://www.sphinx-doc.org/en/master/changes.html#id41). https://github.com/pydata/pydata-sphinx-theme/pull/1029 does the same for pydata-sphinx-theme, but that hasn't been released yet. The 3.6.3 docs were built with Sphinx 5.3.0 and thus didn't get affected (though I'm not entirely sure why, as I just regenerated the venv to create them yesterday.)
